name: 'Workflow of Parent REPO'

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs: 
  trigger_workflow:
    runs_on: ubuntu-latest
    steps:
      - name: Echo Workflow name
        shell: bash
        run: |
          echo "I am Workflow of Parent REPO"